[package]
name = "git-repos"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5", features = ["derive"] }
walkdir = "2.5"
color-eyre = "0.6"
ratatui = "0.29"
crossterm = "0.28"
